### ISSUE TITLE
File naming issues affecting security

### ISSUE THREAD

**Issue by jbash** [asamuzaK/withExEditorHost#14]
File naming bugs affecting security

1.  When you do a "view source" on a file retrieved over HTTP, the filename is derived from the page title. This means a remote Web server has control over the filename *and* the contents.

    This guarantees the ability to take over the user's account and probably the whole computer, provided only that you can trick the user into doing "View Source" on a page you supply. All you have to do is to lead your title with "../../../../../../../../../../../../../../"... and then overwrite any script or configuration file you want.

    It's very dangerous to give a remote server *any* control over *any* part of *any* filename. Sanitizing a filename requires that you know all the special behaviors of every program that might process the name.

2.  When you do a "view source" on a file from the local filesystem, the editor edits the original file.

    This suggests that the extension is passing the messaging host some kind of reference to the file instead of the contents. Reference passing is error prone and tends to lead to security bugs.

3.  At least on Linux, the extension doesn't properly quote the filename when it invokes the editor (for example, if the filename contains spaces, the editor will get an argument for every space-separated word, and will try to open a file for every word in the title).

    The most obvious hack for making this run arbitrary shell commands didn't work on the first try, but that doesn't mean it's not possible to do it. It also means that "view source" doesn't actually work most of the time.

Suggested fix: do both of the following--

1.  Have the messaging host (*not* the browser extension) generate the filename at random, or based on the time or PID or something.

    Do not base the filename on any information that comes from the browser, let alone the remote server. That includes the URL or any of the contents of the file.

    Create a filename that has no spaces or weird characters in it.

2.  Pass the entire text to be edited over the RPC channel between the extension and the messaging host. Do *not* put the data in a file and pass only the filename. In fact, don't pass a filename at all, and don't tell the browser what the filename is.

**Comment by asamuzaK** [comment]
Thanks for your report.

> When you do a "view source" on a file retrieved over HTTP, the filename is derived from the page title. 

It does nothing with page title.
It is based on URI though.
[withExEditor/content.js at master · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/blob/master/src/js/content.js#L793 "withExEditor/content.js at master · asamuzaK/withExEditor")

> When you do a "view source" on a file from the local filesystem, the editor edits the original file.

It is the file URI that is passed from the extension side.
On the host side, I added

* Make sure URI is "file:" protocol
* Make sure local file exists

Is it still insufficient?
[withExEditorHost/index.js at master · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/blob/master/index.js#L320 "withExEditorHost/index.js at master · asamuzaK/withExEditorHost")

> At least on Linux, the extension doesn't properly quote the filename when it invokes the editor (for example, if the filename contains spaces

Fixed in this [commit](https://github.com/asamuzaK/webExtNativeMsg/commit/84e075d81b3e01365a7ffafa6592fb4f5e6c9146 "Refactor ChildProcess.spawn · asamuzaK/webExtNativeMsg@84e075d")
