### ISSUE TITLE
Make tmp file storage location configurable

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditorHost#2]
From [Issue #23 · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues/23#issuecomment-284156239)

> New version is working flawlessly, but I have a feature request — can the storage location for the files be made configurable? The old version stores them in the profile folder, which is persistent in case of a system crash for easy recovery. The new version stores them in `/tmp` on Linux, which on most desktops is not persistent.

**Comment by asamuzaK** [comment]
Currently temporary directory is created from `os.tmpdir()`.
How about
```
const TMP_DIR = process.env.TMP || process.env.TMPDIR ||
                process.env.TEMP || os.tmpdir();
```
which looks for environment variables first?

**Comment by asamuzaK** [comment]
I thought that the example above should be implemented anyway, so I did so.
v1.0.4 / v2.0.0-a.10

Please tell me if this implement solved the issue or not.

**Comment by asamuzaK** [comment]
Needed to fix modules/file-util.js too.
Released v1.0.5 / v2.0.0-a.12

**Comment by wavexx** [comment]
I didn't try with the new version yet, but the version 1.9 creates the temporary directory which is group and world-readable. The main directory should be 700.

Also, when creating temporary files in a system directory (anything but $HOME), you should include the pid of the process to prevent multiple users sharing the same directory. This also means the directory should really be cleaned up properly or put in a volatile storage (such as /tmp), since otherwise multiple directories would creep over time.

**Comment by asamuzaK** [comment]
> The main directory should be 700

Thanks, done.
Directories will be 0o700, files will be 0o600.

v1.0.9 / v2.0.0-a.14

**Comment by asamuzaK** [comment]
@Celti
Look for environment variables first, does this solution meet your needs?

**Comment by asamuzaK** [comment]
I'll close this issue as resolved.
If you still have it, please reopen.
