### ISSUE TITLE
 Can the project support 360 security browser？

### ISSUE THREAD

**Issue by ChenHua20200311** [asamuzaK/withExEditorHost#80]
Can the project support 360 security browser？Thank you first！

**Comment by asamuzaK** [comment]
Some questions:

* In the first place, is it possible to add extension ([withExEditor](https://chrome.google.com/webstore/search/withexeditor?hl=en)) from [Chrome Web Store - Extensions](https://chrome.google.com/webstore/category/extensions?hl=en)?
* If it's possible, what happens if you choose `chrome` when setting up withExEditorHost?
* What is the difference between `360 Security Browser` and `360 Extreme Browser`?
* And which should be supported? Both?

**Comment by asamuzaK** [comment]
I'll close this.
Please reopen if you have any additional info.
